name: Auto Summarizer & Deploy

on:
  push:
    branches:
      - main  # or 'master' if that's your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Summarizer Script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          CI: "true"
        run: |
          python app.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
